syn on
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set number
colorscheme ir_black
set statusline=%-F
set laststatus=2
set ttyfast
set incsearch
set ignorecase
set scrolloff=3
set pastetoggle=<F12>
